version: "3.9"
services:
  db:
    image: materials-api
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: materials
    ports:
      - "3304:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: mysql://root:root@host.docker.internal:3304/materials
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

  frontend:
    build: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

volumes:
  db-data:
