## Récupérer tous les matériaux
GET http://localhost:3000/materiels

### Créer un matériel valide
POST http://localhost:3000/materiels
Content-Type: application/json

{
  "name": "Caméra HD",
  "description": "Caméra 4K",
  "status": "available"
}

### Créer un matériel invalide (422) 
POST http://localhost:3000/materiels
Content-Type: application/json

{
  "title": "oops",
  "email": "not-expected@example.com"
}

### Récupérer un matériel par ID
GET http://localhost:3000/materiels/2

### Modifier un matériel (PATCH)
PATCH http://localhost:3000/materiels/2
Content-Type: application/json

{
  "status": "maintenance"
}

### Supprimer un matériel
DELETE http://localhost:3000/materiels/2
